# Switch Class Driver

ccflags-y  += -I$(srctree)/drivers/huawei_platform/inputhub/iom7/

obj-y += switch_fsa9685_common.o
obj-$(CONFIG_SWITCH_USB_CLS)	+= switch_usb_class.o
obj-$(CONFIG_SWITCH_FSA9685)	+= switch_fsa9685.o
